# Generated by Django 3.0.5 on 2020-04-14 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200413_2320'),
        ('blog', '0004_auto_20200412_2325'),
    ]

    operations = [
    ]
