# Generated by Django 3.0.5 on 2020-04-19 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200419_1324'),
        ('blog', '0005_merge_20200414_1006'),
    ]

    operations = [
    ]
