# Generated by Django 3.0.5 on 2020-04-19 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comment'),
        ('blog', '0009_auto_20200419_1345'),
    ]

    operations = [
    ]
