# Generated by Django 3.0.5 on 2020-04-20 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200419_1745'),
        ('blog', '0011_merge_20200419_1740'),
    ]

    operations = [
    ]
